import React from "react";
import Head from "next/head";

function Layout(props) {
  return (
    <div>
      <Head>
        <title>{props.tittle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {props.children}
    </div>
  );
}

export default Layout;
